[package]
name = "circular-queue"
version = "0.1.2"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
description = "A circular buffer-like queue."
license = "MIT/Apache-2.0"

readme = "README.md"
documentation = "https://docs.rs/circular-queue"
repository = "https://github.com/YaLTeR/circular-queue"
keywords = ["circular", "buffer", "ring", "queue", "container"]
categories = ["data-structures"]

[dependencies]
